defaults: &defaults
  app_name: "MeiYueWuYou"
  foot_html: "&copy; MeiYueWuYou."
  domain: "meiyuewuyou.com"
  email_sender: '85636682@qq.com'
  upyun_username: "meiyuewuyou"
  upyun_password: "hs123456"
  upyun_bucket: "meiyuewuyou"
  upyun_files_bucket: "meiyuewuyou-files"
  upyun_upload_url: "meiyuewuyou.b0.upaiyun.com"
  upyun_upload_files_url: "meiyuewuyou-files.b0.upaiyun.com"
  cdn_url: "meiyuewuyou-file.u.qiniudn.com"
  sms:
    tui3:
      username: 'stephen'
      password: '861117'
    smsbao:
      username: 'stephen'
      password: '861117'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults